import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#444748",
        "tertiary-container": "#e2e2e2",
        "surface-tint": "#c6c6c7",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353434",
        "on-tertiary-container": "#636565",
        "on-secondary-fixed": "#1c1b1d",
        "primary-fixed": "#e2e2e2",
        "on-surface": "#e5e2e1",
        tertiary: "#ffffff",
        "surface-container-low": "#1c1b1b",
        "error-container": "#93000a",
        "on-primary-container": "#636565",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary": "#2f3131",
        "on-background": "#e5e2e1",
        "surface-container": "#201f1f",
        "on-primary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        "on-surface-variant": "#c4c7c8",
        "tertiary-fixed": "#e2e2e2",
        "secondary-fixed": "#e5e1e4",
        "on-primary-fixed-variant": "#454747",
        "on-secondary": "#313032",
        "on-error": "#690005",
        outline: "#8e9192",
        primary: "#ffffff",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#c8c6c8",
        "primary-container": "#e2e2e2",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#c6c6c7",
        background: "#141313",
        surface: "#141313",
        secondary: "#c8c6c8",
        "on-secondary-container": "#b7b4b7",
        "inverse-primary": "#5d5f5f",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#c6c6c7",
        "surface-variant": "#353434",
        "secondary-container": "#474649",
        "surface-dim": "#141313",
        "surface-bright": "#3a3939",
        error: "#ffb4ab",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#474649",
        "on-primary": "#2f3131",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        gutter: "24px",
        "stack-md": "24px",
        "container-max": "1280px",
        "stack-lg": "48px",
        unit: "4px",
        "stack-sm": "8px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-md": ["var(--font-space-grotesk)"],
        "headline-lg": ["var(--font-space-grotesk)"],
        "body-lg": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "display-xl": ["var(--font-space-grotesk)"],
        "label-caps": ["var(--font-inter)"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
